### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by RazyRo** [Strvm/musicxmatch-api#2]
The error message "NameError: name 'proxies' is not defined" the variable proxies has not been defined in the line api = MusixMatchAPI(proxies=proxies).

**Comment by Strvm** [comment]
Hi, could you provide more code please @RazyRo

**Comment by RazyRo** [comment]
# If you need to make a high volume of requests, consider using proxies
from musicxmatch_api import MusixMatchAPI
api = MusixMatchAPI(proxies=proxies)
search = api.search_artist("adele")

**Comment by Strvm** [comment]
Try with:

```
from musicxmatch_api import MusixMatchAPI
api = MusixMatchAPI()
search = api.search_artist("adele")
```

@RazyRo

**Comment by OSehaki** [comment]
does this project still working ? because when i try this doesn't work
